blank_issues_enabled: false
contact_links:
  - name: Question / support
    url: https://github.com/roixe/CesiZen/discussions
    about: Pour une question qui n'est ni un incident ni une demande d'évolution.
