// <auto-generated />
using System;
using CesiZen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CesiZen.Infrastructure.Migrations
{
    [DbContext(typeof(CesiZenDbContext))]
    [Migration("20260212102324_sECCreate")]
    partial class sECCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CesiZen.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DatePublication")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GereParUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("GereParUserId");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("categorie", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Enregistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DureeEffectiveSec")
                        .HasColumnType("int");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("HistoriqueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("HistoriqueId");

                    b.ToTable("enregistre", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Apnee2Sec")
                        .HasColumnType("int");

                    b.Property<int>("ApneeSec")
                        .HasColumnType("int");

                    b.Property<int>("Cycles")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DureeTotaleSec")
                        .HasColumnType("int");

                    b.Property<int>("ExpireSec")
                        .HasColumnType("int");

                    b.Property<int>("InspireSec")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("exercice", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Historique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DureeSec")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("historique", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Maintient", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("UtilisateurId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("maintient", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Article", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CesiZen.Domain.Entities.User", "GereParUser")
                        .WithMany("ArticlesGeres")
                        .HasForeignKey("GereParUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("GereParUser");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Enregistre", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.Exercice", "Exercice")
                        .WithMany("Enregistrements")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CesiZen.Domain.Entities.Historique", "Historique")
                        .WithMany("ExercicesEnregistres")
                        .HasForeignKey("HistoriqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Historique");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Historique", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.User", "Utilisateur")
                        .WithMany("Historiques")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Maintient", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Mainteneurs")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CesiZen.Domain.Entities.User", "Utilisateur")
                        .WithMany("CategoriesMaintenues")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Categorie", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Mainteneurs");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Exercice", b =>
                {
                    b.Navigation("Enregistrements");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Historique", b =>
                {
                    b.Navigation("ExercicesEnregistres");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.User", b =>
                {
                    b.Navigation("ArticlesGeres");

                    b.Navigation("CategoriesMaintenues");

                    b.Navigation("Historiques");
                });
#pragma warning restore 612, 618
        }
    }
}
