// <auto-generated />
using System;
using CesiZen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CesiZen.Infrastructure.Migrations
{
    [DbContext(typeof(CesiZenDbContext))]
    partial class CesiZenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CesiZen.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DatePublication")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GereParUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("GereParUserId");

                    b.ToTable("article", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 2,
                            Contenu = "La respiration lente et régulière stimule le système parasympathique et favorise le retour au calme.",
                            DatePublication = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GereParUserId = 1,
                            Public = true,
                            Titre = "Pourquoi la respiration aide à calmer le stress"
                        });
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("categorie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Respiration"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Gestion du stress"
                        });
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Enregistre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DureeEffectiveSec")
                        .HasColumnType("int");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("HistoriqueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("HistoriqueId");

                    b.ToTable("enregistre", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Apnee2Sec")
                        .HasColumnType("int");

                    b.Property<int>("ApneeSec")
                        .HasColumnType("int");

                    b.Property<int>("Cycles")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DureeTotaleSec")
                        .HasColumnType("int");

                    b.Property<int>("ExpireSec")
                        .HasColumnType("int");

                    b.Property<int>("InspireSec")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("exercice", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apnee2Sec = 0,
                            ApneeSec = 0,
                            Cycles = 30,
                            Description = "Inspire 5s, expire 5s. Environ 5 minutes.",
                            DureeTotaleSec = 300,
                            ExpireSec = 5,
                            InspireSec = 5,
                            Nom = "Cohérence cardiaque 5-5",
                            Public = true,
                            Type = "RESPIRATION"
                        },
                        new
                        {
                            Id = 2,
                            Apnee2Sec = 0,
                            ApneeSec = 7,
                            Cycles = 6,
                            Description = "Inspire 4s, apnée 7s, expire 8s.",
                            DureeTotaleSec = 114,
                            ExpireSec = 8,
                            InspireSec = 4,
                            Nom = "4-7-8",
                            Public = true,
                            Type = "RESPIRATION"
                        },
                        new
                        {
                            Id = 3,
                            Apnee2Sec = 4,
                            ApneeSec = 4,
                            Cycles = 8,
                            Description = "Inspire 4s, apnée 4s, expire 4s, apnée 4s.",
                            DureeTotaleSec = 128,
                            ExpireSec = 4,
                            InspireSec = 4,
                            Nom = "Box breathing 4-4-4-4",
                            Public = true,
                            Type = "RESPIRATION"
                        });
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Historique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DureeSec")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("historique", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Maintient", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("UtilisateurId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("maintient", (string)null);
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateur", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            DateCreation = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cesizen.local",
                            MotDePasseHash = "Admin",
                            Nom = "Admin",
                            Role = "ADMIN"
                        });
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Article", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CesiZen.Domain.Entities.User", "GereParUser")
                        .WithMany("ArticlesGeres")
                        .HasForeignKey("GereParUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("GereParUser");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Enregistre", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.Exercice", "Exercice")
                        .WithMany("Enregistrements")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CesiZen.Domain.Entities.Historique", "Historique")
                        .WithMany("ExercicesEnregistres")
                        .HasForeignKey("HistoriqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Historique");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Historique", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.User", "Utilisateur")
                        .WithMany("Historiques")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Maintient", b =>
                {
                    b.HasOne("CesiZen.Domain.Entities.Categorie", "Categorie")
                        .WithMany("Mainteneurs")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CesiZen.Domain.Entities.User", "Utilisateur")
                        .WithMany("CategoriesMaintenues")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Categorie", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Mainteneurs");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Exercice", b =>
                {
                    b.Navigation("Enregistrements");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.Historique", b =>
                {
                    b.Navigation("ExercicesEnregistres");
                });

            modelBuilder.Entity("CesiZen.Domain.Entities.User", b =>
                {
                    b.Navigation("ArticlesGeres");

                    b.Navigation("CategoriesMaintenues");

                    b.Navigation("Historiques");
                });
#pragma warning restore 612, 618
        }
    }
}
